# Generated by Django 3.1.5 on 2021-01-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20210130_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxfile',
            name='gpx_file',
            field=models.FileField(upload_to='gpx_files'),
        ),
    ]
